# Generated by Django 6.0 on 2026-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='subdomain',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantcustomization',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter'), ('poppins', 'Poppins'), ('montserrat', 'Montserrat'), ('roboto', 'Roboto')], default='poppins', max_length=50),
        ),
    ]
