# Generated by Django 6.0 on 2026-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_menuitem_image_alter_table_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcustomization',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/customization/covers/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_items/'),
        ),
    ]
