# Generated by Django 6.0 on 2026-05-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_restaurantcustomization_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('coadmin', 'Co-administrateur'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='base.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'username')},
            },
        ),
    ]
