# Generated by Django 6.0 on 2026-05-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_refactor_staffmember_add_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_menu_items',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_tables',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('pro', 'Pro'), ('max', 'Max')], max_length=20),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='base.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='base.promocode')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_uses', to='base.restaurant')),
            ],
            options={
                'unique_together': {('promo_code', 'restaurant')},
            },
        ),
    ]
