# Generated by Django 6.0 on 2026-05-06 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subscriptionplan_promo_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_type', models.CharField(choices=[('color', 'Couleur unie'), ('gradient', 'Dégradé'), ('image', 'Image')], default='color', max_length=10)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('bg_gradient_from', models.CharField(default='#f97316', max_length=7)),
                ('bg_gradient_to', models.CharField(default='#ea580c', max_length=7)),
                ('bg_gradient_angle', models.IntegerField(default=135)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='qr_backgrounds/')),
                ('qr_color', models.CharField(default='#000000', max_length=7)),
                ('show_logo', models.BooleanField(default=False)),
                ('output_size', models.IntegerField(default=600)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_settings', to='base.restaurant')),
            ],
        ),
    ]
