# Generated by Django 6.0 on 2026-05-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_qr_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsettings',
            name='qr_scale',
            field=models.IntegerField(default=60, help_text="Taille du QR en % de l'image (10–90)"),
        ),
    ]
