# Generated by Django 6.0 on 2026-05-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_qr_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
