# Generated by Django 6.0 on 2026-05-11 10:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_add_view_count_to_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='media')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='base.menuitem')),
            ],
            options={
                'ordering': ['media_type', 'order'],
            },
        ),
    ]
