# Generated by Django 6.0 on 2026-05-14 16:35

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_add_menuitem_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='token',
            field=models.CharField(default=base.models._generate_table_token, editable=False, max_length=10, unique=True),
        ),
    ]
