# Generated by Django 6.0 on 2026-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_add_waitercall'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mistral', 'Mistral'), ('gemini', 'Gemini')], default='mistral', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(default='mistral-small-latest', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(blank=True)),
                ('max_messages_per_session', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres IA',
                'verbose_name_plural': 'Paramètres IA',
            },
        ),
    ]
