# Generated by Django 6.0 on 2026-07-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_push_subscriptions', to='base.order')),
            ],
            options={
                'unique_together': {('order', 'endpoint')},
            },
        ),
    ]
