# Generated by Django 6.0 on 2026-07-07 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_order_is_paid_order_paid_at_order_paid_by_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('user_role', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(blank=True, default='', max_length=150)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='base.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='base_activi_restaur_92ecca_idx'), models.Index(fields=['restaurant', 'action'], name='base_activi_restaur_6aeb46_idx'), models.Index(fields=['restaurant', 'user'], name='base_activi_restaur_289726_idx')],
            },
        ),
    ]
