# Generated by Django 6.0 on 2026-07-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
