# Generated by Django 6.0 on 2026-07-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_activitylog_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_community_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='base.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='base.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
