# Generated by Django 6.0 on 2026-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_restaurant_google_place_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('openrouter_api_key', models.CharField(blank=True, max_length=255)),
                ('image_model', models.CharField(choices=[('openai/gpt-image-1-mini', 'GPT Image 1 Mini (rapide/éco)'), ('openai/gpt-image-2', 'GPT Image 2 (premium)'), ('google/gemini-2.5-flash-image', 'Gemini 2.5 Flash Image (nano banana)'), ('black-forest-labs/flux-1.1-pro', 'Flux 1.1 Pro'), ('custom', "Autre (saisir l'ID ci-dessous)")], default='openai/gpt-image-1-mini', max_length=100)),
                ('image_model_custom', models.CharField(blank=True, max_length=200)),
                ('image_size', models.CharField(default='1024x1536', max_length=20)),
                ('daily_quota_per_restaurant', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètres génération d'image",
                'verbose_name_plural': "Paramètres génération d'image",
            },
        ),
    ]
