# Generated by Django 6.0 on 2026-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_marketingposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegensettings',
            name='image_model',
            field=models.CharField(choices=[('openai/gpt-image-1-mini', 'GPT Image 1 Mini (le moins cher ~$0.009)'), ('openai/gpt-5-image-mini', 'GPT-5 Image Mini (~$0.033)'), ('google/gemini-3.1-flash-lite-image', 'Gemini 3.1 Flash Lite (~$0.034)'), ('google/gemini-2.5-flash-image', 'Gemini 2.5 Flash Image (nano banana)'), ('google/gemini-3-pro-image', 'Gemini 3 Pro Image (premium)'), ('openai/gpt-5-image', 'GPT-5 Image (premium)'), ('custom', "Autre (saisir l'ID ci-dessous)")], default='openai/gpt-image-1-mini', max_length=100),
        ),
    ]
