# Generated by Django 6.0 on 2026-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_imagegensettings_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured_label',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
