# Generated by Django 6.0 on 2026-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_menuitem_featured_label_menuitem_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('google_api_key', models.CharField(blank=True, max_length=255)),
                ('cache_hours', models.PositiveIntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres réputation (avis Google)',
                'verbose_name_plural': 'Paramètres réputation (avis Google)',
            },
        ),
    ]
