# Generated by Django 6.0 on 2026-07-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_reputationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('stamps_required', models.PositiveIntegerField(default=10)),
                ('reward_label', models.CharField(default='1 récompense', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='base.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('stamps', models.PositiveIntegerField(default=0)),
                ('rewards_redeemed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='base.restaurant')),
            ],
            options={
                'ordering': ['-stamps'],
                'unique_together': {('restaurant', 'phone')},
            },
        ),
    ]
