# Generated by Django 6.0 on 2026-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_order_loyalty_awarded_loyaltyprogram_loyaltycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingposter',
            name='status',
            field=models.CharField(choices=[('generating', 'En cours'), ('done', 'Terminée'), ('failed', 'Échec')], default='done', max_length=12),
        ),
        migrations.AddField(
            model_name='marketingposter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
