# Generated by Django 6.0 on 2026-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_marketingposter_status_marketingposter_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='qrsettings',
            name='bg_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='qr_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='restaurants/covers/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, upload_to='restaurants/logos/'),
        ),
        migrations.AlterField(
            model_name='restaurantcustomization',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='restaurants/customization/covers/'),
        ),
        migrations.AlterField(
            model_name='restaurantcustomization',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='restaurants/customization/logos/'),
        ),
    ]
